### ISSUE TITLE
Linux is not supported any more

### ISSUE THREAD

**Issue by skriesch** [trothr/cmsfs#3]
The build of cmsfs is failing for openSUSE/SLES.
The error message is:
```
[   99s] *** UNAME says this is a Linux system.
[  100s] cmsfssed.sh: this release of Linux is not supported!
```

I took a look to the IBM website and cmsfs should be continuously supported for z/VM.
Is there any update for Linux available?

**Comment by skriesch** [comment]
A patch with updating the kernel version helps.

**Comment by trothr** [comment]
agreed! 
This is a silly bug. 

History: back in the Linux 2.2 days, the CMSFS package included a filesystem driver. The details varied depending on what release of the kernel you were building against. But the FS driver fell out because the author could not keep up with changes to kernel VFS. Eventually IBM wrote a CMS filesystem driver, so the driver function in this package became less needed and all of that logic fell into disrepair. 

I am correcting it now.

**Comment by skriesch** [comment]
It is building fine with your commit now.

One hint about make, cmake and other build tools: We are using, what upstream Maintainers are using and recommending. We are open to switch to cmake, but we are using "what is working for the special upstream project".

I have asked at our Linux Distributions Working Group regarding your history hint: IBM has included drivers into the s390-tools.

**Comment by skriesch** [comment]
SUSE is using your project, because they don't use it via s390-tools until now.

**Comment by trothr** [comment]
Thanks for the report! 

I continue to maintain the project because it allows reading files from CMS disks without having to mount them. It also runs on any Unix/POSIX platform (though I am sure your interest is primarily Linux).

**Comment by trothr** [comment]
This change constitutes release 1.1.11.
